version: "3.8"

services:
  mysql:
    image: mysql:8
    secrets:
      - mysql_root_password
    ports:
      - 3308:3306
    volumes:
      - toh-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: /run/secrets/mysql_root_password
      MYSQL_DATABASE: tour_of_honor

  db-backup:
    image: fradelg/mysql-cron-backup
    secrets:
      - mysql_user
      - mysql_password
    depends_on:
      - mysql
    volumes:
      - toh-mysql-data:/backup
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER_FILE=/run/secrets/mysql_user
      - MYSQL_PASS_FILE=/run/secrets/mysql_password
      - MYSQL_DB=tour_of_honor
      - MAX_BACKUPS=15
      - INIT_BACKUP=0
      # Every day at 3am Eastern (0700 in UTC)
      - CRON_TIME=00 07 * * *
      # Make it small
      - GZIP_LEVEL=9
    restart: unless-stopped

  webapp:
    image: node:16.17
    secrets:
      - mysql_user
      - mysql_password
    command: sh -c "npm ci && npm run dev"
    ports:
      - 3700:3700
    working_dir: /opt/Tour-of-Honor
    volumes:
      - ./:/opt/Tour-of-Honor
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER_FILE: /run/secrets/mysql_user
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
      MYSQL_DB: tour_of_honor

  op-connect-api:
    image: 1password/connect-api:latest
    ports:
      - "8080:8080"
    volumes:
      - "./1password-credentials.json:/home/opuser/.op/1password-credentials.json"
      - "1pwdata:/home/opuser/.op/data"

  op-connect-sync:
    image: 1password/connect-sync:latest
    ports:
      - "8081:8080"
    volumes:
      - "./1password-credentials.json:/home/opuser/.op/1password-credentials.json"
      - "1pwdata:/home/opuser/.op/data"

volumes:
  toh-mysql-data:
  1pwdata:

secrets:
  mysql_root_password:
    file: ./secrets/mysql_root_password
  mysql_user:
    file: ./secrets/mysql_user
  mysql_password:
    file: ./secrets/mysql_password