version: "3.8"
services:
  web:
    build: .
    ports:
      - "3700:8080"
  db:
    image: "mysql"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=VUjpinuBNFwU36
    volumes:
      - db-data:/foo

volumes:
  db-data: